<? 
/* *******************************************************************************************************
MODUL NAME 			: SIMWEB
FILE NAME 			: Users.php
AUTHOR				: MRF
VERSION				: 1.0
MODIFICATION DOC	:
DESCRIPTION			: Entity-base class for tabel Users implementation
***************************************************************************************************** */

  /***
  * Entity-class untuk mengimplementasikan tabel users.
  * 
  * @author M Reza Faisal
  * @generated by Entity Generator 5.8.3
  * @generated on 21-Apr-2005,06:36
  ***/
  include_once("../WEB/classes/base/UsersBase.php");

  class Users extends UsersBase{ 
    var $query;

    /************************** <STANDARD METHODS> **************************************/
    /**
    * Class constructor.
    * @author M Reza Faisal
    **/
    function Users(){
      /** !!DO NOT REMOVE/CHANGE CODES IN THIS SECTION!! **/
      $this->UsersBase(); //execute Entity constructor
      /** YOU CAN INSERT/CHANGE CODES IN THIS SECTION **/				
			
	
    }

    /************************** </STANDARD METHODS> **********************************/

    /************************** <ADDITIONAL METHODS> *********************************/
	function selectByIdPassword($id_usr,$passwd){
      /** YOU CAN INSERT/CHANGE CODES IN THIS SECTION **/
	  //$passwd = md5($passwd."REYZA");
      
	  $str = "
		SELECT 
			USER_APP_ID, A.USER_GROUP_ID, USER_LOGIN, 
			USER_PASS, A.NAMA, ALAMAT, B.NAMA GROUP_NAMA,
			EMAIL, TELEPON, PEGAWAI_ID, 
			A.SATKER_ID, A.SATKER_ID_TAMBAHAN, COALESCE(A.SATKER_ID, A.SATKER_ID_TAMBAHAN) SATKER_ID_MIX, 
			PEGAWAI_PROSES, MASTER_PROSES, LIHAT_PROSES, TEMP_LIST,
			B.IKK_PROSES, B.PENGEMBANGAN_SDM_PROSES, B.POLA_KARIR_PROSES, B.EVALUASI_KINERJA_PROSES, B.TUGAS_BELAJAR_PROSES, B.RENCANA_SUKSESI_PROSES,
			CASE WHEN B.IKK_PROSES = 1 THEN '' ELSE A.SATKER_ID END SATKER_IKK,
			CASE WHEN B.PENGEMBANGAN_SDM_PROSES = 1 THEN '' ELSE A.SATKER_ID END SATKER_PENGEMBANGAN_SDM,
			CASE WHEN B.POLA_KARIR_PROSES = 1 THEN '' ELSE A.SATKER_ID END SATKER_POLA_KARIR,
			CASE WHEN B.EVALUASI_KINERJA_PROSES = 1 THEN '' ELSE A.SATKER_ID END SATKER_EVALUASI_KINERJA,
			CASE WHEN B.TUGAS_BELAJAR_PROSES = 1 THEN '' ELSE A.SATKER_ID END SATKER_TUGAS_BELAJAR,
			CASE WHEN B.RENCANA_SUKSESI_PROSES = 1 THEN '' ELSE A.SATKER_ID END SATKER_RENCANA_SUKSESI
			, B.PENGATURAN_IKK
		FROM user_app A, user_group B 
		WHERE A.USER_GROUP_ID = B.USER_GROUP_ID AND USER_LOGIN='".$id_usr."' AND USER_PASS='".$passwd."'";
   	  //echo $str;exit;
      $this->query = $str;

      return $this->select($str);         
    }
	
	function updatePassword(){
      if(!$this->canUpdate())
        showMessageDlg("Data Users tidak dapat diupdate",true);
      else{
        $this->setField("USER_PASS", md5($this->getField("USER_PASS")));
		$str = "UPDATE user_app 
                SET 
                  USER_PASS = '".$this->getField("USER_PASS")."'
                WHERE 
                  USER_LOGIN = '".$this->getField("USER_LOGIN")."'"; 
        return $this->execQuery($str);
      }
    }
	
	function selectUserGroup($paramsArray=array(),$limit=-1,$from=-1,$varStatement=""){
      $str = "SELECT u.USER_LOGIN AS USER_LOGIN,
	  				 u.NAMA AS NAMA,
					 u.EMAIL AS EMAIL,
					 ug.NAMA as USERGROUP
	  		  FROM user_app u, user_group ug
			  WHERE USER_LOGIN IS NOT NULL 
					AND ug.USER_GROUP_ID = u.USER_GROUP_ID "; 
      while(list($key,$val)=each($paramsArray)){
        $str .= " AND $key = '$val' ";
      }
      $str .= $varStatement." ORDER BY u.USER_LOGIN";
	  $this->query = $str;
      return $this->selectLimit($str,$limit,$from); 
    }
	
	function searchUserGroup($paramsArray=array(),$limit=-1,$from=-1,$varStatement=""){
      $str = "SELECT u.USER_LOGIN AS USER_LOGIN,
	  				 u.NAMA AS NAMA,
					 u.EMAIL AS EMAIL,
					 ug.NAMA as USERGROUP
	  		  FROM user_app u, user_group ug
			  WHERE USER_LOGIN IS NOT NULL 
					AND ug.USER_GROUP_ID = u.USER_GROUP_ID "; 
      while(list($key,$val)=each($paramsArray)){
        $str .= " AND $key LIKE '%$val%' ";
      }
      $str .= $varStatement." ORDER BY u.USER_LOGIN";
	  $this->query = $str;
      return $this->selectLimit($str,$limit,$from); 
    }
	
	function getSearchCountByParams($paramsArray=array(),$varStatement=""){
      $str = "SELECT COUNT(USER_LOGIN) AS ROWCOUNT FROM user_app WHERE USER_LOGIN IS NOT NULL ".$varStatement; 
      while(list($key,$val)=each($paramsArray)){
        $str .= " AND $key LIKE '%$val%' ";
      }
      $this->select($str); 
      if($this->firstRow()) 
        return $this->getField("ROWCOUNT"); 
      else 
         return 0; 
    }

    /************************** </ADDITIONAL METHODS> *******************************/
  } //end of class Users
?>