<?

function getarray($mode)
{
	if($mode == "jadwalacaraasesorview")
	{
		$arrkolomdata= array(
	        array("val"=>"reqCatalogId", "field"=>"JADWAL_ASESOR_ID")
			, array("val"=>"reqCheckDelete", "field"=>"")
			, array("val"=>"reqLineNo", "field"=>"")
			, array("val"=>"reqAsesorId", "field"=>"ASESOR_ID")
			, array("val"=>"reqAsesorNama", "field"=>"ASESOR_NAMA")
			, array("val"=>"reqBatasPegawai", "field"=>"BATAS_PEGAWAI")
			, array("val"=>"reqKeterangan", "field"=>"KETERANGAN_JADWAL")
	    );
	}
	elseif($mode == "jadwalacaraasesoradd")
	{
		$arrkolomdata= array(
	        array("val"=>"reqCatalogId", "field"=>"JADWAL_ASESOR_ID")
			, array("val"=>"reqCheckDelete", "field"=>"")
			, array("val"=>"reqLineNo", "field"=>"")
			, array("val"=>"reqAsesorId", "field"=>"ASESOR_ID")
			, array("val"=>"reqAsesorNama", "field"=>"")
			, array("val"=>"reqBatasPegawai", "field"=>"BATAS_PEGAWAI")
			, array("val"=>"reqKeterangan", "field"=>"KETERANGAN")
	    );
	}
	elseif($mode == "jadwalacarapegawaiview")
	{
		$arrkolomdata= array(
	        array("val"=>"reqCatalogId", "field"=>"JADWAL_PEGAWAI_ID")
			, array("val"=>"reqCheckDelete", "field"=>"")
			, array("val"=>"reqLineNo", "field"=>"")
			, array("val"=>"reqAsesorId", "field"=>"JADWAL_ASESOR_ID")
			, array("val"=>"reqPegawaiId", "field"=>"PEGAWAI_ID")
			, array("val"=>"reqNipPegawai", "field"=>"PEGAWAI_NIP")
			, array("val"=>"reqPegawaiNama", "field"=>"PEGAWAI_NAMA")
			, array("val"=>"reqEselon", "field"=>"PEGAWAI_ESELON")
			, array("val"=>"reqJabatan", "field"=>"PEGAWAI_JAB_STRUKTURAL")

	    );
	}
	elseif($mode == "jadwalacarapegawaiadd")
	{
		$arrkolomdata= array(
	         array("val"=>"reqCatalogId", "field"=>"JADWAL_PEGAWAI_ID")
			, array("val"=>"reqCheckDelete", "field"=>"")
			, array("val"=>"reqLineNo", "field"=>"")
			, array("val"=>"reqAsesorId", "field"=>"JADWAL_ASESOR_ID")
			, array("val"=>"reqPegawaiId", "field"=>"PEGAWAI_ID")
			, array("val"=>"reqNipPegawai", "field"=>"PEGAWAI_NIP")
			, array("val"=>"reqPegawaiNama", "field"=>"")
			, array("val"=>"reqEselon", "field"=>"PEGAWAI_ESELON")
			, array("val"=>"reqJabatan", "field"=>"PEGAWAI_JAB_STRUKTURAL")
	    );
	}
	/*elseif($mode == "mr")
	{
		$arrkolomdata= array(
	        array("val"=>"reqCatalogId", "field"=>"ID")
			, array("val"=>"reqCheckDelete", "field"=>"")
			, array("val"=>"reqLineNo", "field"=>"")
			, array("val"=>"reqMrDetilStatus", "field"=>"")
			, array("val"=>"reqProductTypeId", "field"=>"INV_PR_ITEM_TYPE_ID")
			, array("val"=>"reqProductType", "field"=>"PRODUCT_TYPE")
			, array("val"=>"reqType", "field"=>"TYPE")
			, array("val"=>"reqPrTypeNama", "field"=>"INV_PR_ITEM_TYPE_NAMA")
			, array("val"=>"reqProductId", "field"=>"PRODUCT_ID")
			, array("val"=>"reqServiceId", "field"=>"SERVICE_ID")
			, array("val"=>"reqMaterialCode", "field"=>"PRODUCT_CODE")
			, array("val"=>"reqMaterialNama", "field"=>"PRODUCT_NAMA")
			, array("val"=>"reqMaterialDesc", "field"=>"PRODUCT_DESCRIPTION")
			, array("val"=>"reqQtyAvailable", "field"=>"QTY_LEFT_PR")
			, array("val"=>"reqQty", "field"=>"QTY_LEFT_PR")
			, array("val"=>"reqUomId", "field"=>"UOM_PR_ID")
			, array("val"=>"reqUomNama", "field"=>"UOM_PR_NAMA")
			, array("val"=>"reqPrice", "field"=>"")
			, array("val"=>"reqAgreemenNama", "field"=>"")
			, array("val"=>"reqAgreemenItem", "field"=>"")
			, array("val"=>"reqVendorId", "field"=>"PARTNER_ID")
			, array("val"=>"reqVendorNama", "field"=>"PARTNER_NAME")
			, array("val"=>"reqDateRequired", "field"=>"DATE_REQUIRED")
			, array("val"=>"reqReqTrakingNumber", "field"=>"")
			, array("val"=>"reqRegionalId", "field"=>"REGIONAL_ID")
			, array("val"=>"reqRegionalNama", "field"=>"REGIONAL_NAME")
			, array("val"=>"reqUnitId", "field"=>"UNIT_ID")
			, array("val"=>"reqUnitNama", "field"=>"UNIT_NAME")
			, array("val"=>"reqWhId", "field"=>"WH_ID")
			, array("val"=>"reqWhNama", "field"=>"WH_NAMA")
			, array("val"=>"reqIdStorage", "field"=>"STORAGE_ID")
			, array("val"=>"reqStorage", "field"=>"STORAGE_CODE")
			, array("val"=>"reqRequistor", "field"=>"")
			, array("val"=>"reqAmount", "field"=>"AMOUNT")
			, array("val"=>"reqAccAssType", "field"=>"ACC_LINE_TIPE")
			, array("val"=>"reqAccountId", "field"=>"ACCOUNT_ID")
			, array("val"=>"reqAccountNama", "field"=>"ACCOUNT_CODE")
			, array("val"=>"reqComitAccId", "field"=>"COMIT_ACC_ID")
			, array("val"=>"reqComitAccNama", "field"=>"COMIT_ACC_CODE")
			, array("val"=>"reqCostCenterId", "field"=>"COST_CENTER_ID")
			, array("val"=>"reqCostCenterNama", "field"=>"COST_CENTER_CODE")
			, array("val"=>"reqFundCenterId", "field"=>"FUND_CENTER_ID")
			, array("val"=>"reqFundCenterNama", "field"=>"FUND_CENTER_NAMA")
			, array("val"=>"reqWbs", "field"=>"")
			, array("val"=>"reqNetwork", "field"=>"")
			, array("val"=>"reqOrder", "field"=>"")
			, array("val"=>"reqMrDoc", "field"=>"DOC_NO")
			, array("val"=>"reqMrLineNo", "field"=>"LINE_NO")
			, array("val"=>"reqMrId", "field"=>"MR_ID")
			, array("val"=>"reqMrLineId", "field"=>"MR_LINE_ID")
			, array("val"=>"reqMrQty", "field"=>"QTY")
			, array("val"=>"reqMrUomId", "field"=>"UOM_ID")
			, array("val"=>"reqMrUom", "field"=>"UOM_NAMA")
			, array("val"=>"reqMrUomPrRate", "field"=>"UOM_PR_RATE")
			, array("val"=>"reqIsClosed", "field"=>"IS_CLOSED")
			, array("val"=>"reqMaterialValueUpdating", "field"=>"VALUE_UPDATING")
	        , array("val"=>"reqMaterialQuantityUpdating", "field"=>"QUANTITY_UPDATING")
	    );
	}
	elseif($mode == "adddata")
	{
		$arrkolomdata= array(
			array("val"=>"reqCatalogId", "field"=>"ID")
			, array("val"=>"reqCheckDelete", "field"=>"")
			, array("val"=>"reqLineNo", "field"=>"LINE_NO")
			, array("val"=>"reqMrDetilStatus", "field"=>"")
			, array("val"=>"reqProductTypeId", "field"=>"PR_ITEM_TYPE_ID")
			, array("val"=>"reqProductType", "field"=>"")
			, array("val"=>"reqType", "field"=>"TYPE")
			, array("val"=>"reqPrTypeNama", "field"=>"PR_ITEM_TYPE")
			, array("val"=>"reqProductId", "field"=>"PRODUCT_ID")
			, array("val"=>"reqServiceId", "field"=>"SERVICE_ID")
			, array("val"=>"reqMaterialCode", "field"=>"")
			, array("val"=>"reqMaterialNama", "field"=>"")
			, array("val"=>"reqMaterialDesc", "field"=>"DESCRIPTION")
			, array("val"=>"reqQtyAvailable", "field"=>"")
			, array("val"=>"reqQty", "field"=>"QTY")
			, array("val"=>"reqUomId", "field"=>"UOM_ID")
			, array("val"=>"reqUomNama", "field"=>"")
			, array("val"=>"reqPrice", "field"=>"PRICE")
			, array("val"=>"reqAgreemenNama", "field"=>"OA_ID")
			, array("val"=>"reqAgreemenItem", "field"=>"OA_LINE")
			, array("val"=>"reqVendorId", "field"=>"PARTNER_ID")
			, array("val"=>"reqVendorNama", "field"=>"PARTNER_NAME")
			, array("val"=>"reqDateRequired", "field"=>"DATE_REQUIRED")
			, array("val"=>"reqReqTrakingNumber", "field"=>"")
			, array("val"=>"reqRegionalId", "field"=>"REGIONAL_ID")
			, array("val"=>"reqRegionalNama", "field"=>"REGIONAL_NAME")
			, array("val"=>"reqUnitId", "field"=>"UNIT_ID")
			, array("val"=>"reqUnitNama", "field"=>"UNIT_NAME")
			, array("val"=>"reqWhId", "field"=>"WH_ID")
			, array("val"=>"reqWhNama", "field"=>"")
			, array("val"=>"reqIdStorage", "field"=>"STORAGE_ID")
			, array("val"=>"reqStorage", "field"=>"")
			, array("val"=>"reqRequistor", "field"=>"")
			, array("val"=>"reqAmount", "field"=>"AMOUNT")
			, array("val"=>"reqAccAssType", "field"=>"ACC_LINE_TIPE")
			, array("val"=>"reqAccountId", "field"=>"ACCOUNT_ID")
			, array("val"=>"reqAccountNama", "field"=>"")
			, array("val"=>"reqComitAccId", "field"=>"COMIT_ACC_ID")
			, array("val"=>"reqComitAccNama", "field"=>"")
			, array("val"=>"reqCostCenterId", "field"=>"COST_CENTER_ID")
			, array("val"=>"reqCostCenterNama", "field"=>"")
			, array("val"=>"reqFundCenterId", "field"=>"FUND_CENTER_ID")
			, array("val"=>"reqFundCenterNama", "field"=>"")
			, array("val"=>"reqWbs", "field"=>"")
			, array("val"=>"reqNetwork", "field"=>"")
			, array("val"=>"reqOrder", "field"=>"")
			, array("val"=>"reqMrDoc", "field"=>"")
			, array("val"=>"reqMrLineNo", "field"=>"")
			, array("val"=>"reqMrId", "field"=>"MR_ID")
			, array("val"=>"reqMrLineId", "field"=>"MR_LINE_ID")
			, array("val"=>"reqMrQty", "field"=>"")
			, array("val"=>"reqMrUomId", "field"=>"")
			, array("val"=>"reqMrUom", "field"=>"")
			, array("val"=>"reqMrUomPrRate", "field"=>"")
			, array("val"=>"reqIsClosed", "field"=>"")
			, array("val"=>"reqMaterialValueUpdating", "field"=>"VALUE_UPDATING")
	        , array("val"=>"reqMaterialQuantityUpdating", "field"=>"QUANTITY_UPDATING")
	    );
	}*/
	
    return $arrkolomdata;
}

?>
