<? 
/* *******************************************************************************************************
MODUL NAME 			: SIMWEB
FILE NAME 			: UsersBase.php
AUTHOR				: MRF
VERSION				: 1.0
MODIFICATION DOC	:
DESCRIPTION			: Entity-base class for tabel Users implementation
***************************************************************************************************** */

  /***
  * Entity-base class untuk mengimplementasikan tabel Users.
  * 
  * @author M Reza Faisal
  * @generated by Entity Generator 5.8.3
  * @generated on 27-Apr-2005,14:15
  ***/
  include_once("../WEB/classes/db/Entity.php");

  class IntegrasiBaru extends Entity{ 

	var $query;
	var $db;
    /**
    * Class constructor.
    * @author M Reza Faisal
    **/
    function IntegrasiBaru(){
	  
	  $xmlfile = "../WEB/web.xml";
	  $data = simplexml_load_file($xmlfile);
	  $rconf_url_info= $data->urlConfig->main->urlbase;

	  $this->db=$rconf_url_info;
	  	
      $this->Entity(); 
    }

    /**
    * Cek apakah operasi insert dapat dilakukan atau tidak 
    * @author M Reza Faisal
    * @return boolean True jika insert boleh dilakukan, false jika tidak.
    **/
    function canInsert(){
      return true;
    }

    /**
    * Insert record ke database. 
    * @author M Reza Faisal
    * @return boolean True jika insert sukses, false jika tidak.
    **/
		function selectByParamsMonitoring($paramsArray=array(),$limit=-1,$from=-1, $statement="", $sOrder="ORDER BY pegawai_id ASC"){
	   $str = "
			SELECT 
				*
			FROM simpeg.pegawai
			WHERE 1=1"; 
      while(list($key,$val)=each($paramsArray)){
        $str .= " AND $key = '$val' ";
      }
      $str .= $statement."".$sOrder;
      $this->query = $str;
      return $this->selectLimit($str,$limit,$from); 
    }

    function selectByParamsRiwayatPendidikan($paramsArray=array(),$limit=-1,$from=-1, $statement="", $sOrder=" ORDER BY a.pendidikan_id asc"){
	   $str = "
			SELECT c.nama nama_pegawai, c.nip_baru nip_pegawai, b.NAMA pendidikan_nama
			FROM data.riwayat_pendidikan a
			left join simpeg.pendidikan b on a.pendidikan_id=b.pendidikan_id
			left join simpeg.pegawai c on a.pegawai_id=c.pegawai_id
			WHERE 1=1"; 
      while(list($key,$val)=each($paramsArray)){
        $str .= " AND $key = '$val' ";
      }
      $str .= $statement."".$sOrder;
	  	$this->query = $str;
      return $this->selectLimit($str,$limit,$from); 
    }

    function selectByParamsRiwayatHukdis($paramsArray=array(),$limit=-1,$from=-1, $statement="", $sOrder=" ORDER BY a.tahun asc"){
	   $str = "
			SELECT c.nama nama_pegawai, c.nip_baru nip_pegawai, a.tahun
			FROM data.riwayat_hukdis a
			left join simpeg.pegawai c on a.pegawai_id=c.pegawai_id
			WHERE 1=1"; 
      while(list($key,$val)=each($paramsArray)){
        $str .= " AND $key = '$val' ";
      }
      $str .= $statement."".$sOrder;
	  	$this->query = $str;
      return $this->selectLimit($str,$limit,$from); 
    }

    function selectByParamsRiwayatSKP($paramsArray=array(),$limit=-1,$from=-1, $statement="", $sOrder=" ORDER BY a.tahun asc"){
	   $str = "
			SELECT a.*
			FROM data.riwayat_skp a
			left join simpeg.pegawai c on a.pegawai_id=c.pegawai_id
			WHERE 1=1"; 
      while(list($key,$val)=each($paramsArray)){
        $str .= " AND $key = '$val' ";
      }
      $str .= $statement."".$sOrder;
	  	$this->query = $str;
      return $this->selectLimit($str,$limit,$from); 
    }

    function selectByParamsRiwayatPenghargaan($paramsArray=array(),$limit=-1,$from=-1, $statement="", $sOrder=" ORDER BY a.tanggal asc"){
	   $str = "
			SELECT a.*
			FROM data.riwayat_penghargaan a
			WHERE 1=1"; 
      while(list($key,$val)=each($paramsArray)){
        $str .= " AND $key = '$val' ";
      }
      $str .= $statement."".$sOrder;
	  	$this->query = $str;
      return $this->selectLimit($str,$limit,$from); 
    }
	
		function getCountByParamsMonitoring($paramsArray=array(), $Statement="")
		{
			$str = "SELECT COUNT(1) AS ROWCOUNT FROM simpeg.pegawai WHERE 1=1 ".$statement; 
			while(list($key,$val)=each($paramsArray))
			{
				$str .= " AND $key = '$val' ";
			}
			
			$this->select($str); 
			if($this->firstRow()) 
				return $this->getField("ROWCOUNT"); 
			else 
				return 0; 
    }

    function insertSKP()
		{
			/*Auto-generate primary key(s) by next max value (integer) */
			$this->setField("RIWAYAT_SKP_ID", $this->getNextId("RIWAYAT_SKP_ID","data.RIWAYAT_SKP")); 

			$str = "INSERT INTO data.RIWAYAT_SKP (
					   RIWAYAT_SKP_ID, TAHUN, PEGAWAI_ID, NILAI_PENGUKURAN, RATA_PERILAKU, NILAI_SKP, NILAI_KINERJA,HASIL_KARYA, PERILAKU_KERJA, KINERJA_PEGAWAI, STATUS_FILE, FILE_SKP, PENILAI, NIP_PENILAI,ATASAN_PENILAI, NIP_ATASAN_PENILAI) 
					VALUES (
					  '".$this->getField("RIWAYAT_SKP_ID")."',
					  ".$this->getField("TAHUN").",
					  (select pegawai_id from simpeg.pegawai where nip_baru='".$this->getField("NIP_BARU")."'),
					  ".$this->getField("NILAI_PENGUKURAN").",
					  ".$this->getField("RATA_PERILAKU").",
					  ".$this->getField("NILAI_SKP").",
					  ".$this->getField("NILAI_KINERJA").",
					  ".$this->getField("HASIL_KARYA").",
					  ".$this->getField("PERILAKU_KERJA").",
					  ".$this->getField("KINERJA_PEGAWAI").",
					  '".$this->getField("STATUS_FILE")."',
					  '".$this->getField("FILE_SKP")."',
					  '".$this->getField("PENILAI")."',
					  '".$this->getField("NIP_PENILAI")."',
					  '".$this->getField("ATASAN_PENILAI")."',
					  '".$this->getField("NIP_ATASAN_PENILAI")."'
					)"; 
					// echo $str;
			// $this->id= $this->getField("JADWAL_ASESOR_ID");
			$this->query= $str;
			return $this->execQuery($str);
    }

    function deleteskp(){
      $str = "DELETE FROM data.riwayat_skp";
      return $this->execQuery($str);
    }

    function insertPenghargaan()
		{
			/*Auto-generate primary key(s) by next max value (integer) */
			$this->setField("RIWAYAT_PENGHARGAAN_ID", $this->getNextId("RIWAYAT_PENGHARGAAN_ID","data.RIWAYAT_PENGHARGAAN")); 

			$str = "INSERT INTO data.RIWAYAT_PENGHARGAAN (
					   RIWAYAT_PENGHARGAAN_ID, PEGAWAI_ID, NAMA_PENGHARGAAN, PENGHARGAAN_ID, TANGGAL,STATUS_FILE, FILE_PENGHARGAAN) 
					VALUES (
					  '".$this->getField("RIWAYAT_PENGHARGAAN_ID")."',
					  (select pegawai_id from simpeg.pegawai where nip_baru='".$this->getField("NIP_BARU")."'),
					  '".$this->getField("penghargaan")."',
					  ".$this->getField("id_penghargaan").",
					  ".$this->getField("tgl_penghargaan").",
					  '".$this->getField("STATUS_FILE")."',
					  '".$this->getField("FILE_PENGHARGAAN")."'
					)"; 
					// echo $str;
			// $this->id= $this->getField("JADWAL_ASESOR_ID");
			$this->query= $str;
			return $this->execQuery($str);
    }

    function deletepenghargaan(){
      $str = "DELETE FROM data.riwayat_penghargaan";
      return $this->execQuery($str);
    }
  } 
?>