<? 
/* *******************************************************************************************************
MODUL NAME 			: SIMWEB
FILE NAME 			: UsersBase.php
AUTHOR				: MRF
VERSION				: 1.0
MODIFICATION DOC	:
DESCRIPTION			: Entity-base class for tabel Users implementation
***************************************************************************************************** */

  /***
  * Entity-base class untuk mengimplementasikan tabel Users.
  * 
  * @author M Reza Faisal
  * @generated by Entity Generator 5.8.3
  * @generated on 27-Apr-2005,14:15
  ***/
  include_once("../WEB/classes/db/Entity.php");

  class UsersBase extends Entity{ 

	var $query;
	var $db;
    /**
    * Class constructor.
    * @author M Reza Faisal
    **/
    function UsersBase(){
	  
	  $xmlfile = "../WEB/web.xml";
	  $data = simplexml_load_file($xmlfile);
	  $rconf_url_info= $data->urlConfig->main->urlbase;

	  $this->db=$rconf_url_info;
	  	
      $this->Entity(); 
    }

    /**
    * Cek apakah operasi insert dapat dilakukan atau tidak 
    * @author M Reza Faisal
    * @return boolean True jika insert boleh dilakukan, false jika tidak.
    **/
    function canInsert(){
      return true;
    }

    /**
    * Insert record ke database. 
    * @author M Reza Faisal
    * @return boolean True jika insert sukses, false jika tidak.
    **/
    function insert(){
      if(!$this->canInsert())
        showMessageDlg("Data Users tidak dapat di-insert",true);
      else{
	  	/*Auto-generate primary key(s) by next max value (integer) */
		$this->setField("USER_APP_ID", $this->getNextId("USER_APP_ID","user_app"));
        $this->setField("USER_PASS", md5($this->getField("USER_PASS")));
		$str = "
		INSERT INTO user_app (
		   USER_APP_ID, USER_GROUP_ID, USER_LOGIN, 
		   USER_PASS, NAMA, ALAMAT, 
		   EMAIL, TELEPON, PEGAWAI_ID, SATKER_ID, LAST_CREATE_USER, LAST_CREATE_DATE, LAST_CREATE_SATKER, SATKER_ID_TAMBAHAN) 
		VALUES (
				  '".$this->getField("USER_APP_ID")."',
                  '".$this->getField("USER_GROUP_ID")."',
                  '".$this->getField("USER_LOGIN")."',
                  '".$this->getField("USER_PASS")."',
                  '".$this->getField("NAMA")."',
                  '".$this->getField("ALAMAT")."',
				  '".$this->getField("EMAIL")."',
				  '".$this->getField("TELEPON")."',
				  '".$this->getField("PEGAWAI_ID")."', 
				  '".$this->getField("SATKER_ID")."',				 
				  '".$this->getField("LAST_CREATE_USER")."',
				  ".$this->getField("LAST_CREATE_DATE").",
				  '".$this->getField("LAST_CREATE_SATKER")."',
				  '".$this->getField("SATKER_ID_TAMBAHAN")."'	
                )"; 
		$this->query = $str;
        return $this->execQuery($str);
      }
    }
	
	function insertCapeg(){
      if(!$this->canInsert())
        showMessageDlg("Data Users tidak dapat di-insert",true);
      else{
	  	/*Auto-generate primary key(s) by next max value (integer) */
		$this->setField("USER_APP_ID", $this->getNextId("USER_APP_ID","user_app"));
        $this->setField("USER_PASS", md5("admin"));
		$str = "
		INSERT INTO user_app (
		   USER_APP_ID, USER_GROUP_ID, USER_LOGIN, 
		   USER_PASS, NAMA, ALAMAT, 
		   EMAIL, TELEPON, PEGAWAI_ID, SATKER_ID, LAST_CREATE_USER, LAST_CREATE_DATE, LAST_CREATE_SATKER, SATKER_ID_TAMBAHAN) 
		VALUES (
				  '".$this->getField("USER_APP_ID")."',
                  '1',
                  '".$this->getField("USER_LOGIN")."',
                  '".$this->getField("USER_PASS")."',
                  '".$this->getField("NAMA")."',
                  '".$this->getField("ALAMAT")."',
				  '".$this->getField("EMAIL")."',
				  '".$this->getField("TELEPON")."',
				  '".$this->getField("PEGAWAI_ID")."', 
				  NULL,
				  '".$this->getField("LAST_CREATE_USER")."',
				  ".$this->getField("LAST_CREATE_DATE").",
				  '".$this->getField("LAST_CREATE_SATKER")."',
				  '".$this->getField("SATKER_ID_TAMBAHAN")."'	
                )"; 
		$this->query = $str;
        return $this->execQuery($str);
      }
    }
	
    /**
    * Cek apakah operasi update dapat dilakukan atau tidak. 
    * @author M Reza Faisal
    * @return boolean True jika update dapat dilakukan, false jika tidak.
    **/
    function canUpdate(){
      return true;
    }

    /**
    * Update record. 
    * @author M Reza Faisal
    * @return boolean True jika update sukses, false jika tidak.
    **/
    function update(){
      if(!$this->canUpdate())
        showMessageDlg("Data Users tidak dapat diupdate",true);
      else{
        $this->setField("USER_PASS", md5($this->getField("USER_PASS")));
		$str = "
				UPDATE user_app
				SET    USER_GROUP_ID = '".$this->getField("USER_GROUP_ID")."',
					   USER_LOGIN    = '".$this->getField("USER_LOGIN")."',
					   USER_PASS     = '".$this->getField("USER_PASS")."',
					   NAMA          = '".$this->getField("NAMA")."',
					   ALAMAT        = '".$this->getField("ALAMAT")."',
					   EMAIL         = '".$this->getField("EMAIL")."',
					   TELEPON       = '".$this->getField("TELEPON")."',
					   PEGAWAI_ID    = 0,
					   SATKER_ID	 = '".$this->getField("SATKER_ID")."',
					  LAST_UPDATE_USER	= '".$this->getField("LAST_UPDATE_USER")."',
					  LAST_UPDATE_DATE	= ".$this->getField("LAST_UPDATE_DATE").",
					  LAST_UPDATE_SATKER = '".$this->getField("LAST_UPDATE_SATKER")."',
					  SATKER_ID_TAMBAHAN = '".$this->getField("SATKER_ID_TAMBAHAN")."'
				WHERE  USER_APP_ID   = '".$this->getField("USER_APP_ID")."'
				"; 
		$this->query = $str;
		//echo $str;
        return $this->execQuery($str);
      }
    }
	
	function update_user(){
      if(!$this->canUpdate())
        showMessageDlg("Data Users tidak dapat diupdate",true);
      else{
		$str = "
				UPDATE user_app
				SET    USER_GROUP_ID = '".$this->getField("USER_GROUP_ID")."',
					   USER_LOGIN    = '".$this->getField("USER_LOGIN")."',
					   NAMA          = '".$this->getField("NAMA")."',
					   SATKER_ID	 = '".$this->getField("SATKER_ID")."',
					  LAST_UPDATE_USER	= '".$this->getField("LAST_UPDATE_USER")."',
					  LAST_UPDATE_DATE	= ".$this->getField("LAST_UPDATE_DATE").",
					  LAST_UPDATE_SATKER	= '".$this->getField("LAST_UPDATE_SATKER")."',
					  SATKER_ID_TAMBAHAN = '".$this->getField("SATKER_ID_TAMBAHAN")."'					   
				WHERE  USER_APP_ID   = '".$this->getField("USER_APP_ID")."'
				"; 
		$this->query = $str;
		//echo $str;
        return $this->execQuery($str);
      }
    }
	
	function updateNoPass(){
      if(!$this->canUpdate())
        showMessageDlg("Data Users tidak dapat diupdate",true);
      else{
		$str = "
				UPDATE user_app
				SET    USER_GROUP_ID = '".$this->getField("USER_GROUP_ID")."',
					   NAMA          = '".$this->getField("NAMA")."',
					   ALAMAT        = '".$this->getField("ALAMAT")."',
					   EMAIL         = '".$this->getField("EMAIL")."',
					   TELEPON       = '".$this->getField("TELEPON")."',
					   PEGAWAI_ID    = '".$this->getField("PEGAWAI_ID")."',
					   SATKER_ID	 = '".$this->getField("SATKER_ID")."',
					   SATKER_ID_TAMBAHAN = '".$this->getField("SATKER_ID_TAMBAHAN")."'
				WHERE  USER_APP_ID   = '".$this->getField("USER_APP_ID")."'
				"; 
				  //echo $str;
				  $this->query = $str;
        return $this->execQuery($str);
      }
    }

    /**
    * Cek apakah record dapat dihapus atau tidak. 
    * @author M Reza Faisal
    * @return boolean True jika record dapat dihapus, false jika tidak.
    **/
    function canDelete(){
      return true;
    }

    /**
    * Menghapus record sesuai id-nya. 
    * @author M Reza Faisal
    * @return boolean True jika penghapusan sukses, false jika tidak.
    **/
    function delete(){
      if(!$this->canDelete())
        showMessageDlg("Data Users tidak dapat di-hapus",true);
      else{
        $str = "DELETE FROM user_app 
                WHERE 
                  USER_APP_ID = '".$this->getField("USER_APP_ID")."'"; 
        return $this->execQuery($str);
      }
    }

    function updatePassword()
	{
		$this->setField("USER_PASS", md5($this->getField("USER_PASS")));
		/*Auto-generate primary key(s) by next max value (integer) */
		$str = "UPDATE user_app SET
				  USER_PASS = '".$this->getField("USER_PASS")."',
				  LAST_UPDATE_USER	= '".$this->getField("LAST_UPDATE_USER")."',
				  LAST_UPDATE_DATE	= ".$this->getField("LAST_UPDATE_DATE").",
				  LAST_UPDATE_SATKER	= '".$this->getField("LAST_UPDATE_SATKER")."'
				WHERE USER_APP_ID = '".$this->getField("USER_APP_ID")."'
				"; 
		$this->query = $str;
		return $this->execQuery($str);
    }
    /**
    * Cari record berdasarkan id-nya. 
    * @author M Reza Faisal
    * @param string USER_LOGIN Id record 
    * @return boolean True jika pencarian sukses, false jika tidak.
    **/
    function selectById($username){
      $str = "SELECT * FROM user_app
              WHERE 
                USER_LOGIN = '".$username."'"; 
				
		$this->query = $str;
      return $this->select($str);
    }

    /** 
    * Cari record berdasarkan array parameter dan limit tampilan 
    * @author M Reza Faisal
    * @param array paramsArray Array of parameter. Contoh array("id"=>"xxx","nama"=>"yyy") 
    * @param int limit Jumlah maksimal record yang akan diambil 
    * @param int from Awal record yang diambil 
    * @return boolean True jika sukses, false jika tidak 
    **/ 
    function selectByParams($paramsArray=array(),$limit=-1,$from=-1){
      $str = "SELECT * FROM user_app WHERE USER_LOGIN IS NOT NULL "; 
      while(list($key,$val)=each($paramsArray)){
        $str .= " AND $key = '$val' ";
      }
      $str .= " ORDER BY USER_LOGIN";
	  //echo $str;
      return $this->selectLimit($str,$limit,$from); 
    }
	
	function insertModif()
	{
		/*Auto-generate primary key(s) by next max value (integer) */
		$this->setField("USER_APP_ID", $this->getNextId("USER_APP_ID","user_app")); 

		$str = "
				INSERT INTO user_app(
					   USER_APP_ID, USER_GROUP_ID, 
					   NAMA, USER_LOGIN, USER_PASS, PEGAWAI_ID, SATKER_ID, SATKER_ID_TAMBAHAN) 
  			 	VALUES (
					  ".$this->getField("USER_APP_ID").",
					  ".$this->getField("USER_GROUP_ID").",
					  '".$this->getField("NAMA")."',
					  '".$this->getField("USER_LOGIN")."',
					  '".md5($this->getField("USER_PASS"))."',
					  ".$this->getField("PEGAWAI_ID").",
					  '".$this->getField("SATKER_ID")."',
					  '".$this->getField("SATKER_ID_TAMBAHAN")."'
				)"; 	
		$this->query = $str;
		
		return $this->execQuery($str);
    }

    function updateModif()
	{
		/*Auto-generate primary key(s) by next max value (integer) */
		$str = "
				UPDATE user_app
				SET     
					   USER_LOGIN		= '".$this->getField("USER_LOGIN")."',
					   USER_GROUP_ID	= ".$this->getField("USER_GROUP_ID").",					   
					   NAMA				= '".$this->getField("NAMA")."',
					   TELEPON			= '".$this->getField("TELEPON")."',				   
					   PEGAWAI_ID		= ".$this->getField("PEGAWAI_ID").",
					   SATKER_ID		= '".$this->getField("SATKER_ID")."',
					   SATKER_ID_TAMBAHAN = '".$this->getField("SATKER_ID_TAMBAHAN")."'
				WHERE USER_APP_ID		= ".$this->getField("USER_APP_ID")."
 				"; 

				$this->query = $str;
		return $this->execQuery($str);
    }
	
	function resetPassword()
	{
		/*Auto-generate primary key(s) by next max value (integer) */
		$str = "UPDATE user_app A SET
				 	   USER_PASS= '".md5($this->getField("USER_PASS"))."'
				WHERE USER_APP_ID= ".$this->getField("USER_APP_ID")."
				"; 
				$this->query = $str;
	//echo $str;
		return $this->execQuery($str);
    }
	
	function selectByParamsMonitoring($paramsArray=array(),$limit=-1,$from=-1, $statement="", $sOrder="ORDER BY A.USER_LOGIN"){
	   $str = "
			SELECT 
				A.USER_APP_ID, A.NAMA, A.PEGAWAI_ID, A.USER_LOGIN, A.SATKER_ID, A.SATKER_ID_TAMBAHAN, 
				A.USER_GROUP_ID, B.NAMA USER_GROUP_NAMA, C.NAMA PEGAWAI_NAMA, '' SATKER_NAMA
			FROM user_app A
			LEFT JOIN user_group B ON B.USER_GROUP_ID = A.USER_GROUP_ID
			LEFT JOIN asesor C ON C.ASESOR_ID = A.PEGAWAI_ID
			WHERE 1=1"; 
      while(list($key,$val)=each($paramsArray)){
        $str .= " AND $key = '$val' ";
      }
      $str .= $statement."".$sOrder;
	  $this->query = $str;
      return $this->selectLimit($str,$limit,$from); 
    }
	
	function getCountByParamsMonitoring($paramsArray=array(), $varStatement=""){
      $str = "
	  SELECT COUNT(1) AS ROWCOUNT 
	  FROM user_app A
	  LEFT JOIN user_group B ON B.USER_GROUP_ID = A.USER_GROUP_ID
	  WHERE 1=1 ".$varStatement; 
      while(list($key,$val)=each($paramsArray)){
        $str .= " AND $key = '$val' ";
      }
	  $this->query = $str;
      $this->select($str); 
      if($this->firstRow()) 
        return $this->getField("ROWCOUNT"); 
      else 
         return 0; 
    }
	
	function selectByParamsMonitorLog($paramsArray=array(),$limit=-1,$from=-1, $user_login="", $statement="", $sOrder="ORDER BY TO_CHAR(TANGGAL, 'DD-MM-YYYY HH24:MI:SS') DESC"){
	   $str = "
		   SELECT * FROM (
			SELECT 'Menambah data Agama pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM agama where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Agama pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM agama where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Anak pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM ANAK where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Anak pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM ANAK where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Anjab pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM ANJAB where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Anjab pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM ANJAB where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Anjab Detil pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM ANJAB_DETIL where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Anjab Detil pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM ANJAB_DETIL where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Bahasa pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM BAHASA where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Bahasa Detil pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM BAHASA where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Bank pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM bank where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Bank Detil pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM bank where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Cuti pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM CUTI where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Cuti pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM CUTI where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Diklat Fungsional pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM DIKLAT_FUNGSIONAL where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Diklat Fungsional pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM DIKLAT_FUNGSIONAL where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Diklat Struktural pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM DIKLAT_STRUKTURAL where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Diklat Struktural pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM DIKLAT_STRUKTURAL where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Diklat Teknis pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM DIKLAT_TEKNIS where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Diklat Teknis pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM DIKLAT_TEKNIS where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Daftar Urutan Kepegawaian pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM DUK where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Daftar Urutan Kepegawaian pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM DUK where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Eselon pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM ESELON where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Eselon pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM ESELON where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Gaji Pegawai pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM GAJI_PEGAWAI where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Gaji Pegawai pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM GAJI_PEGAWAI where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Gaji Pokok pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM GAJI_POKOK where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Gaji Pokok pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM GAJI_POKOK where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Gaji Riwayat pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM GAJI_RIWAYAT where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Gaji Riwayat pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM GAJI_RIWAYAT where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Hukuman pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM HUKUMAN where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Hukuman pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM HUKUMAN where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Hutang SKPP pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM HUTANG_SKPP where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Hutang SKPP pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM HUTANG_SKPP where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Jabatan Fungsional pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM JABATAN_FUNGSIONAL where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Jabatan Fungsional pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM JABATAN_FUNGSIONAL where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Jabatan Riwayat pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM jabatan_riwayat where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Jabatan Riwayat pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM jabatan_riwayat where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Jenis Hukuman pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM JENIS_HUKUMAN where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Jenis Hukuman pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM JENIS_HUKUMAN where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Jenis Pegawai pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM JENIS_PEGAWAI where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Jenis Pegawai pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM JENIS_PEGAWAI where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Jurusan Pendidikan pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM JURUSAN_PENDIDIKAN where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Jurusan Pendidikan pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM JURUSAN_PENDIDIKAN where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Kabupaten pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM kabupaten where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Kabupaten pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM kabupaten where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Kecamatan pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM kecamatan where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Kecamatan pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM kecamatan where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Kedudukan pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM kedudukan where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Kedudukan pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM kedudukan where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Kelurahan pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM kelurahan where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Kelurahan pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM kelurahan where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Kenaikan Pangkat pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM KENAIKAN_PANGKAT where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Kenaikan Pangkat pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM KENAIKAN_PANGKAT where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Kenaikan Pangkat Detil pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM KENAIKAN_PANGKAT_DETIL where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Kenaikan Pangkat Detil pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM KENAIKAN_PANGKAT_DETIL where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Kenaikan Gaji Berkala pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM KGB where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Kenaikan Gaji Berkala pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM KGB where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Korpri pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM KORPRI where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Korpri pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM KORPRI where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Kenaikan Pangkat pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM KP where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Kenaikan Pangkat pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM KP where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Kenaikan Pangkat Usulan pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM KP_USULAN where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Kenaikan Pangkat Usulan pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM KP_USULAN where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Kursus pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM KURSUS where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Kursus pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM KURSUS where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Lencana pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM LENCANA where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Lencana pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM LENCANA where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Lencana Pegawai pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM LENCANA_PEGAWAI where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Lencana Pegawai pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM LENCANA_PEGAWAI where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Mertua pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM MERTUA where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Mertua pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM MERTUA where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Mutasi pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM MUTASI where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Mutasi pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM MUTASI where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Nikah Riwayat pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM NIKAH_RIWAYAT where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Nikah Riwayat pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM NIKAH_RIWAYAT where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Orang Tua pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM ORANG_TUA where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Orang Tua pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM ORANG_TUA where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Organisasi Riwayat pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM ORGANISASI_RIWAYAT where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Organisasi Riwayat pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM ORGANISASI_RIWAYAT where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Pangkat pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PANGKAT where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Pangkat pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PANGKAT where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Pangkat Riwayat pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PANGKAT_RIWAYAT where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Pangkat Riwayat pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PANGKAT_RIWAYAT where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Parameter Gaji pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PARAMETER_GAJI where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Parameter Gaji pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PARAMETER_GAJI where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Pejabat Penetap pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM pejabat_penetap where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Pejabat Penetap pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM pejabat_penetap where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Penataran pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PENATARAN where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Penataran pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PENATARAN where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Pendidikan pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PENDIDIKAN where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Pendidikan pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PENDIDIKAN where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Pendidikan Riwayat pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM pendidikan_riwayat where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Pendidikan Riwayat pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM pendidikan_riwayat where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Pengalaman pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PENGALAMAN where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Pengalaman pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PENGALAMAN where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Penghargaan pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PENGHARGAAN where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Penghargaan pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PENGHARGAAN where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Penilaian pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PENILAIAN where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Penilaian pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PENILAIAN where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Pensiun pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PENSIUN where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Pensiun pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PENSIUN where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Peraturan pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PERATURAN where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Peraturan pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PERATURAN where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Perubahan Data pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PERUBAHAN_DATA where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Perubahan Data pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PERUBAHAN_DATA where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Piagam pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PIAGAM where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Piagam pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PIAGAM where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Potensi Diri pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM POTENSI_DIRI where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Potensi Diri pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM POTENSI_DIRI where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Prestasi Kerja pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PRESTASI_KERJA where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Prestasi Kerja pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PRESTASI_KERJA where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Propinsi pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM propinsi where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Propinsi pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM propinsi where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Satuan Kerja pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM satker where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Satuan Kerja pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM satker where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Saudara pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM SAUDARA where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Saudara pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM SAUDARA where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Seminar pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM SEMINAR where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Seminar pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM SEMINAR where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data SK Cpns pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM SK_CPNS where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data SK Cpns pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM SK_CPNS where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data SK Pns pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM SK_PNS where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data SK Pns pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM SK_PNS where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Status Pegawai pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM status_pegawai where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Status Pegawai pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM status_pegawai where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Suami / Istri pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM SUAMI_ISTRI where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Suami / Istri pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM SUAMI_ISTRI where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Tambahan Masa Kerja pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM TAMBAHAN_MASA_KERJA where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Tambahan Masa Kerja pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM TAMBAHAN_MASA_KERJA where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Tingkat Hukuman pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM TINGKAT_HUKUMAN where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Tingkat Hukuman pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM TINGKAT_HUKUMAN where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Tipe Pegawai pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM tipe_pegawai where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Tipe Pegawai pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM tipe_pegawai where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Toefl pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM TOEFL where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Toefl pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM TOEFL where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Tugas pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM TUGAS where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Tugas pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM TUGAS where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Tugas Belajar pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM TUGAS_BELAJAR where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Tugas Belajar pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM TUGAS_BELAJAR where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Tunjangan Umum pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM TUNJANGAN_UMUM where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Tunjangan Umum pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM TUNJANGAN_UMUM where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data User Aplikasi pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM user_app where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data User Aplikasi pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM user_app where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data User Group Aplikasi pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM user_group where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data User Group Aplikasi pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM user_group where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Visitor pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM VISITOR where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Visitor pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM VISITOR where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data ZIS pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM ZIS where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data ZIS pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM ZIS where LAST_UPDATE_USER = '".$user_login."'
			) A WHERE 1=1
	   "; 
      $str .= $statement." ".$sOrder;
	  $this->query = $str;
	  //echo $str;
      return $this->selectLimit($str,$limit,$from); 
    }
	
    /** 
    * Hitung jumlah record berdasarkan parameter (array). 
    * @author M Reza Faisal
    * @param array paramsArray Array of parameter. Contoh array("id"=>"xxx","nama"=>"yyy") 
    * @return long Jumlah record yang sesuai kriteria 
    **/ 
	
	function getCountByParamsMonitorLog($paramsArray=array(), $user_login="", $statement=""){
	  
	  $str= "
	  		SELECT COUNT(AKSI) AS ROWCOUNT FROM (
			SELECT 'Menambah data Agama pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM agama where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Agama pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM agama where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Anak pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM ANAK where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Anak pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM ANAK where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Anjab pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM ANJAB where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Anjab pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM ANJAB where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Anjab Detil pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM ANJAB_DETIL where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Anjab Detil pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM ANJAB_DETIL where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Bahasa pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM BAHASA where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Bahasa Detil pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM BAHASA where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Bank pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM bank where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Bank Detil pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM bank where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Cuti pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM CUTI where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Cuti pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM CUTI where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Diklat Fungsional pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM DIKLAT_FUNGSIONAL where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Diklat Fungsional pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM DIKLAT_FUNGSIONAL where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Diklat Struktural pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM DIKLAT_STRUKTURAL where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Diklat Struktural pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM DIKLAT_STRUKTURAL where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Diklat Teknis pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM DIKLAT_TEKNIS where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Diklat Teknis pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM DIKLAT_TEKNIS where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Daftar Urutan Kepegawaian pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM DUK where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Daftar Urutan Kepegawaian pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM DUK where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Eselon pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM ESELON where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Eselon pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM ESELON where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Gaji Pegawai pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM GAJI_PEGAWAI where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Gaji Pegawai pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM GAJI_PEGAWAI where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Gaji Pokok pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM GAJI_POKOK where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Gaji Pokok pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM GAJI_POKOK where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Gaji Riwayat pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM GAJI_RIWAYAT where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Gaji Riwayat pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM GAJI_RIWAYAT where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Hukuman pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM HUKUMAN where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Hukuman pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM HUKUMAN where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Hutang SKPP pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM HUTANG_SKPP where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Hutang SKPP pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM HUTANG_SKPP where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Jabatan Fungsional pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM JABATAN_FUNGSIONAL where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Jabatan Fungsional pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM JABATAN_FUNGSIONAL where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Jabatan Riwayat pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM jabatan_riwayat where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Jabatan Riwayat pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM jabatan_riwayat where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Jenis Hukuman pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM JENIS_HUKUMAN where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Jenis Hukuman pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM JENIS_HUKUMAN where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Jenis Pegawai pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM JENIS_PEGAWAI where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Jenis Pegawai pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM JENIS_PEGAWAI where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Jurusan Pendidikan pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM JURUSAN_PENDIDIKAN where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Jurusan Pendidikan pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM JURUSAN_PENDIDIKAN where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Kabupaten pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM kabupaten where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Kabupaten pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM kabupaten where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Kecamatan pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM kecamatan where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Kecamatan pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM kecamatan where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Kedudukan pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM kedudukan where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Kedudukan pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM kedudukan where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Kelurahan pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM kelurahan where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Kelurahan pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM kelurahan where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Kenaikan Pangkat pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM KENAIKAN_PANGKAT where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Kenaikan Pangkat pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM KENAIKAN_PANGKAT where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Kenaikan Pangkat Detil pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM KENAIKAN_PANGKAT_DETIL where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Kenaikan Pangkat Detil pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM KENAIKAN_PANGKAT_DETIL where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Kenaikan Gaji Berkala pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM KGB where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Kenaikan Gaji Berkala pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM KGB where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Korpri pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM KORPRI where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Korpri pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM KORPRI where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Kenaikan Pangkat pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM KP where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Kenaikan Pangkat pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM KP where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Kenaikan Pangkat Usulan pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM KP_USULAN where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Kenaikan Pangkat Usulan pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM KP_USULAN where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Kursus pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM KURSUS where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Kursus pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM KURSUS where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Lencana pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM LENCANA where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Lencana pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM LENCANA where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Lencana Pegawai pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM LENCANA_PEGAWAI where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Lencana Pegawai pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM LENCANA_PEGAWAI where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Mertua pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM MERTUA where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Mertua pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM MERTUA where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Mutasi pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM MUTASI where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Mutasi pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM MUTASI where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Nikah Riwayat pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM NIKAH_RIWAYAT where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Nikah Riwayat pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM NIKAH_RIWAYAT where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Orang Tua pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM ORANG_TUA where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Orang Tua pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM ORANG_TUA where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Organisasi Riwayat pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM ORGANISASI_RIWAYAT where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Organisasi Riwayat pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM ORGANISASI_RIWAYAT where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Pangkat pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PANGKAT where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Pangkat pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PANGKAT where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Pangkat Riwayat pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PANGKAT_RIWAYAT where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Pangkat Riwayat pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PANGKAT_RIWAYAT where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Parameter Gaji pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PARAMETER_GAJI where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Parameter Gaji pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PARAMETER_GAJI where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Pejabat Penetap pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM pejabat_penetap where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Pejabat Penetap pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM pejabat_penetap where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Penataran pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PENATARAN where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Penataran pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PENATARAN where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Pendidikan pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PENDIDIKAN where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Pendidikan pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PENDIDIKAN where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Pendidikan Riwayat pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM pendidikan_riwayat where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Pendidikan Riwayat pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM pendidikan_riwayat where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Pengalaman pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PENGALAMAN where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Pengalaman pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PENGALAMAN where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Penghargaan pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PENGHARGAAN where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Penghargaan pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PENGHARGAAN where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Penilaian pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PENILAIAN where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Penilaian pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PENILAIAN where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Pensiun pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PENSIUN where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Pensiun pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PENSIUN where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Peraturan pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PERATURAN where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Peraturan pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PERATURAN where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Perubahan Data pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PERUBAHAN_DATA where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Perubahan Data pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PERUBAHAN_DATA where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Piagam pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PIAGAM where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Piagam pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PIAGAM where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Potensi Diri pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM POTENSI_DIRI where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Potensi Diri pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM POTENSI_DIRI where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Prestasi Kerja pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM PRESTASI_KERJA where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Prestasi Kerja pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM PRESTASI_KERJA where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Propinsi pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM propinsi where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Propinsi pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM propinsi where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Satuan Kerja pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM satker where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Satuan Kerja pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM satker where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Saudara pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM SAUDARA where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Saudara pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM SAUDARA where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Seminar pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM SEMINAR where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Seminar pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM SEMINAR where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data SK Cpns pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM SK_CPNS where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data SK Cpns pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM SK_CPNS where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data SK Pns pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM SK_PNS where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data SK Pns pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM SK_PNS where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Status Pegawai pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM status_pegawai where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Status Pegawai pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM status_pegawai where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Suami / Istri pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM SUAMI_ISTRI where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Suami / Istri pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM SUAMI_ISTRI where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Tambahan Masa Kerja pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM TAMBAHAN_MASA_KERJA where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Tambahan Masa Kerja pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM TAMBAHAN_MASA_KERJA where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Tingkat Hukuman pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM TINGKAT_HUKUMAN where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Tingkat Hukuman pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM TINGKAT_HUKUMAN where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Tipe Pegawai pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM tipe_pegawai where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Tipe Pegawai pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM tipe_pegawai where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Toefl pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM TOEFL where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Toefl pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM TOEFL where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Tugas pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM TUGAS where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Tugas pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM TUGAS where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Tugas Belajar pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM TUGAS_BELAJAR where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Tugas Belajar pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM TUGAS_BELAJAR where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Tunjangan Umum pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM TUNJANGAN_UMUM where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Tunjangan Umum pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM TUNJANGAN_UMUM where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data User Aplikasi pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM user_app where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data User Aplikasi pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM user_app where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data User Group Aplikasi pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM user_group where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data User Group Aplikasi pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM user_group where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data Visitor pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM VISITOR where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data Visitor pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM VISITOR where LAST_UPDATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Menambah data ZIS pada tanggal ' || TO_CHAR(LAST_CREATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_CREATE_DATE TANGGAL FROM ZIS where LAST_CREATE_USER = '".$user_login."'
			UNION ALL
			SELECT 'Mengubah data ZIS pada tanggal ' || TO_CHAR(LAST_UPDATE_DATE, 'DD-MM-YYYY HH24:MI:SS') AKSI, LAST_UPDATE_DATE TANGGAL FROM ZIS where LAST_UPDATE_USER = '".$user_login."'
			) A WHERE 1=1
	   "; 
      $str .= $statement;
	  $this->query = $str;
      $this->select($str); 
      if($this->firstRow()) 
        return $this->getField("ROWCOUNT"); 
      else 
         return 0; 
    }
	
	
    function getCountByParams($paramsArray=array(), $varStatement=""){
      $str = "SELECT COUNT(USER_LOGIN) AS ROWCOUNT FROM user_app WHERE USER_LOGIN IS NOT NULL ".$varStatement; 
      while(list($key,$val)=each($paramsArray)){
        $str .= " AND $key = '$val' ";
      }
      $this->select($str); 
      if($this->firstRow()) 
        return $this->getField("ROWCOUNT"); 
      else 
         return 0; 
    }
	
	function getJenis($varCID)
	{
		$this->selectByParams(array('user_id' => $varCID));
		$this->firstRow();
		
		return $this->getField('jenis');
	}
	
	function getHp($varCID)
	{
		$this->selectByParams(array('satuan_kerja_id' => $varCID));
		$this->firstRow();
		
		return $this->getField('hp');
	}
	
	function getEmail($varCID)
	{
		$this->selectByParams(array('satuan_kerja_id' => $varCID));
		$this->firstRow();
		
		return $this->getField('email');
	}
  } 
?>