<?
function selectsatuankerjainternal()
{
	$arraydata= array("SEKRETARIAT JENDRAL", "INSPEKTORAT JENDRAL", "DITJEN PERHUBUNGAN DARAT", "DITJEN PERHUBUNGAN LAUT", "DITJEN PERHUBUNGAN UDARA", "BADAN PENGEMBANGAN SDM PERHUBUNGAN", "BADAN PENELITIAN DAN PENGEMBANGAN", "DITJEN PERHUBUNGAN UDARA", "BADAN PENGEMBANGAN SDM PERHUBUNGAN", "BADAN PENELITIAN DAN PENGEMBANGAN", "BADAN SAR NASIONAL", "DITJEN PERKERETAAPIAN", "BADAN PENGELOLA TRANS JABODETABEK", "BADAN SAR NASIONAL");

	return $arraydata;
}
?>